const flights = [
  {
    id:1,
    flightNum:34534,
    departFrom:"Israel",
    image:'https://www.ynetnews.com/PicServer4/2016/05/10/6995374/11.jpg',
    landOn:"USA",
    numOfSits:45,
    ETAtime:"18:40",
    arrivalTime:"23:00",
    isFirstClass:false,
    sitsAvailable:20
  },
  {
    id:2,
    flightNum:4565,
    departFrom:"TLV",
    image:'https://reloadvisor.org/wp-content/uploads/2019/10/NY-ReloAdvisor.org_.jpg',
    landOn:"NY",
    numOfSits:50,
    ETAtime:"12:00",
    arrivalTime:"2300",
    isFirstClass:true,
    sitsAvailable:8
  },
  {
    id:3,
    flightNum:4354634,
    departFrom:"LA",
    image:'https://media.timeout.com/images/105211701/image.jpg',
    landOn:"Rome",
    numOfSits:56,
    ETAtime:"5:00",
    arrivalTime:"18:00",
    isFirstClass:false,
    sitsAvailable:6
  },
  {
    id:4,
    flightNum:4353454,
    departFrom:"London",
    image:'https://www.afdb.org/sites/default/files/east_africa_.jpg',
    landOn:"AFRICA",
    numOfSits:55,
    ETAtime:"16:50",
    arrivalTime:"20:55",
    isFirstClass:false,
    sitsAvailable:4
  }
]

module.exports = flights;